set(ARDUINO_UNO_PROTOCOL "arduino")
set(ARDUINO_UNO_BOARD "standard")
set(ARDUINO_UNO_MCU "atmega328p")
set(ARDUINO_UNO_FCPU "16000000")
set(ARDUINO_UNO_UPLOAD_SPEED "115200")
set(ARDUINO_UNO_PORT "/dev/ttyACM0")
set(ARDUINO_UNO_ROOT "$ENV{HOME}.arduino15/packages/arduino")
set(CMAKE_C_COMPILER "${ARDUINO_UNO_ROOT}/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/avr-gcc")
set(CMAKE_CXX_COMPILER "${ARDUINO_UNO_ROOT}/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/avr-g++")
set(ARDUINO_UNO_OBJCOPY "${ARDUINO_UNO_ROOT}/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/avr-objcopy")
set(ARDUINO_UNO_AVRDUDE "${ARDUINO_UNO_ROOT}/tools/avrdude/6.3.0-arduino8/bin/avrdude")
include(${CMAKE_SOURCE_DIR}/scripts/libarduino_uno.cmake)
