set(ARDUINO_MEGA_PROTOCOL "wiring")
set(ARDUINO_MEGA_BOARD "mega")
set(ARDUINO_MEGA_MCU "atmega2560")
set(ARDUINO_MEGA_FCPU "16000000L")
set(ARDUINO_MEGA_UPLOAD_SPEED "115200")
set(ARDUINO_MEGA_PORT "/dev/ttyACM0")
set(ARDUINO_MEGA_ROOT "$ENV{HOME}.arduino15/packages/arduino")
set(CMAKE_C_COMPILER "${ARDUINO_MEGA_ROOT}/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/avr-gcc")
set(CMAKE_CXX_COMPILER "${ARDUINO_MEGA_ROOT}/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/avr-g++")
set(ARDUINO_MEGA_OBJCOPY "${ARDUINO_MEGA_ROOT}/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/avr-objcopy")
set(ARDUINO_MEGA_AVRDUDE "${ARDUINO_MEGA_ROOT}/tools/avrdude/6.3.0-arduino8/bin/avrdude")
include(${CMAKE_SOURCE_DIR}/scripts/libarduino_mega.cmake)
